### ISSUE TITLE
Enable LGTM

### ISSUE THREAD

**Issue by tboerger** [drone-plugins/drone-marathon#6]
@bradrydzewski

**Comment by dellintosh** [comment]
@tboerger / @bradrydzewski we have been using a custom python module for v0.4, is this one considered "Ready for v0.5"?  If not, I'll plan to update our version so we can keep using Drone in our CI/CD pipeline.

Thanks again for all your hard work on this!

**Comment by tboerger** [comment]
@dellintosh pretty much the wrong topic to ask that. But to answer your question, this plugin is available for drone >= 0.5, it have never been done for an older version.

**Comment by tboerger** [comment]
LGTM is dead, closing
