### ISSUE TITLE
Make it possible to deploy a manifest directly

### ISSUE THREAD

**Issue by onbjerg** [drone-plugins/drone-marathon#7]
It would be nice if you could avoid having this parameter chaos and just enable deploying a manifest directly, something akin [drone-kube](https://github.com/vallard/drone-kube).

**Comment by onbjerg** [comment]
Actually, I see that [e20co/drone-marathon@drone-0.5](https://github.com/e20co/drone-marathon/tree/drone-0.5) does this.

Maybe we should just use that instead, since it is also more actively maintained than this repository?

**Comment by tboerger** [comment]
This plugin is not really actively maintained anymore, I gonna close that issue. If somebody with marathon knowledge and also some test environment wants to volunteer raise your hand.
